### PR TITLE
Added option to calculate error and correlation on the median

### PR DESCRIPTION
**Pull request by dloney**

### CODE REVIEW

**Comment by rileyhales** [comment]
This looks alright to me @waderoberts123 and @rfun. Let me know when you've had a chance to look it over.

**Review by rileyhales — APPROVED** [review]

**Comment by dloney** [comment]
It looks like this is failing on older numba builds. Can it still be merged in since that is independent of this feature?

**Comment by dloney** [comment]
Looks like there's also a discrepancy in the mean error metric for one of the tests. Since this defaults to the existing functionality, the inclusion of the median shouldn't have caused the issue. Additionally, #35 is affected by the same issue without any changes to the function. I would suggest a separate pull request to fix the test issue.

**Comment by rileyhales** [comment]
I'm going to merge this. the tests failing don't have anything to do with these changes and i think they're ok. we don't need to wait any longer.

**Pull request merged**
